import assert from 'node:assert/strict';
import { test } from 'vitest';
import {
  fs,
  path,
  runCli,
  runCommand,
  withTempDir,
} from './helpers/cli-contract-helpers.mjs';

async function initializeProject(dir) {
  const git = await runCommand(dir, 'git', ['init', '-q']);
  assert.equal(git.code, 0, git.stderr || git.stdout);
  await fs.mkdir(path.join(dir, 'docs', 'features'), { recursive: true });
  await fs.writeFile(
    path.join(dir, 'docs', '.lee-spec-kit.json'),
    `${JSON.stringify(
      {
        projectName: 'demo',
        projectType: 'single',
        lang: 'ko',
        docsRepo: 'embedded',
        experimental: { openwiki: true },
        workflow: { mode: 'local', baseBranch: 'main' },
      },
      null,
      2
    )}\n`
  );
}

test('knowledge ci scaffolds direct OpenWiki execution and writing guidance', async () => {
  await withTempDir('lsk-knowledge-ci-', async (dir) => {
    await initializeProject(dir);

    const result = await runCli(dir, ['knowledge', 'ci', '--json']);
    assert.equal(result.code, 0, result.stderr || result.stdout);
    const payload = JSON.parse(result.stdout);
    const workflow = await fs.readFile(payload.path, 'utf8');
    const instructions = await fs.readFile(payload.instructions, 'utf8');
    const ignore = await fs.readFile(payload.ignore, 'utf8');

    assert.equal(payload.executionOwner, 'openwiki');
    assert.equal(payload.instructionsCreated, true);
    assert.equal(payload.ignoreUpdated, true);
    assert.match(ignore, /\/AGENTS\.md\n\/CLAUDE\.md/u);
    assert.match(workflow, /openwiki code --update --print --language ko/u);
    assert.doesNotMatch(workflow, /lee-spec-kit knowledge update/u);
    assert.doesNotMatch(
      workflow,
      /Avoid repeating a failed scheduled revision/u
    );
    assert.match(
      instructions,
      /\/skills\/lee-spec-kit-technical-writing\/SKILL\.md/u
    );

    const customInstructions = '# Project-owned instructions\n';
    await fs.writeFile(payload.instructions, customInstructions);
    const repeated = await runCli(dir, ['knowledge', 'ci', '--json']);
    assert.equal(repeated.code, 0, repeated.stderr || repeated.stdout);
    assert.equal(JSON.parse(repeated.stdout).instructionsCreated, false);
    assert.equal(JSON.parse(repeated.stdout).ignoreUpdated, false);
    assert.equal(
      await fs.readFile(payload.instructions, 'utf8'),
      customInstructions
    );
  });
});

test('knowledge ci enables auto-merge only when requested', async () => {
  await withTempDir('lsk-knowledge-auto-merge-', async (dir) => {
    await initializeProject(dir);
    const result = await runCli(dir, [
      'knowledge',
      'ci',
      '--auto-merge',
      '--json',
    ]);
    assert.equal(result.code, 0, result.stderr || result.stdout);
    const payload = JSON.parse(result.stdout);
    const workflow = await fs.readFile(payload.path, 'utf8');
    assert.match(workflow, /gh pr merge --auto --squash/u);
  });
});

test('knowledge ci replaces only the recognized legacy generated workflow', async () => {
  await withTempDir('lsk-knowledge-ci-migrate-', async (dir) => {
    await initializeProject(dir);
    const workflowPath = path.join(
      dir,
      '.github',
      'workflows',
      'lee-spec-kit-knowledge.yml'
    );
    await fs.mkdir(path.dirname(workflowPath), { recursive: true });
    await fs.writeFile(
      workflowPath,
      '# Generated by lee-spec-kit. Configure OPENAI_API_KEY in repository secrets.\n# Avoid repeating a failed scheduled revision\n# lee-spec-kit knowledge update --ci\n'
    );

    const migrated = await runCli(dir, ['knowledge', 'ci', '--json']);
    assert.equal(migrated.code, 0, migrated.stderr || migrated.stdout);
    assert.equal(JSON.parse(migrated.stdout).workflowUpdated, true);
    assert.match(
      await fs.readFile(workflowPath, 'utf8'),
      /openwiki code --update/u
    );

    await fs.writeFile(workflowPath, 'name: custom-openwiki\n');
    const refused = await runCli(dir, ['knowledge', 'ci', '--json']);
    assert.notEqual(refused.code, 0);
    assert.match(refused.stdout, /OPENWIKI_CI_EXISTS/u);
    assert.equal(
      await fs.readFile(workflowPath, 'utf8'),
      'name: custom-openwiki\n'
    );
  });
});
