import { Command } from 'commander';
import { randomUUID } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import fs from 'fs-extra';
import { getConfig } from '../utils/config.js';
import { createCliError, toCliError } from '../utils/cli-error.js';
import { resolveFeatureSelection } from '../utils/feature-resolver.js';
import {
  buildCuratedImpactGrandfatherMarker,
  computeFeatureDocumentationFingerprint,
  isTerminalFeatureForCuratedImpact,
  parseCuratedDocumentationImpact,
  removeCuratedImpactGrandfatherMarkers,
} from '../utils/documentation-impact.js';
import { buildKnowledgeWorkflow } from '../utils/knowledge-ci.js';
import { isOpenWikiEnabled } from '../utils/openwiki-policy.js';
import {
  resolveGitPrimaryWorktreeRoot,
  resolveStandaloneProjectRoots,
} from '../utils/standalone-workspace.js';
import { getDocsLockPath, withFileLock } from '../utils/lock.js';
import { getResourcesDir } from '../utils/paths.js';

const KNOWLEDGE_IGNORE_BEGIN = '# lee-spec-kit:knowledge-source-ignore:begin';
const KNOWLEDGE_IGNORE_END = '# lee-spec-kit:knowledge-source-ignore:end';
const KNOWLEDGE_IGNORE_BLOCK = `${KNOWLEDGE_IGNORE_BEGIN}\n/AGENTS.md\n/CLAUDE.md\n${KNOWLEDGE_IGNORE_END}`;

interface KnowledgeOptions {
  component?: string;
  json?: boolean;
  apply?: boolean;
  autoMerge?: boolean;
}

export function knowledgeCommand(program: Command): void {
  const knowledge = program
    .command('knowledge')
    .description(
      'Scaffold independent OpenWiki CI and migrate documentation policy'
    );

  knowledge
    .command('ci')
    .description(
      'Write a scheduled OpenWiki workflow; does not run or manage OpenWiki'
    )
    .option(
      '--component <component>',
      'Component name for standalone multi projects'
    )
    .option(
      '--auto-merge',
      'Enable auto-merge for completed Knowledge PRs; requires protected branch checks'
    )
    .option('--json', 'Output JSON')
    .action(async (options: KnowledgeOptions) => {
      await handleKnowledgeAction(options, async () => {
        const config = await getConfig(process.cwd());
        if (!config)
          throw createCliError('CONFIG_NOT_FOUND', 'Run init first.');
        if (!isOpenWikiEnabled(config)) {
          throw createCliError(
            'OPENWIKI_DISABLED',
            'Enable experimental.openwiki first.'
          );
        }
        const roots =
          config.docsRepo === 'standalone'
            ? resolveStandaloneProjectRoots(config, options.component)
            : [resolveGitPrimaryWorktreeRoot(config.docsDir)];
        if (roots.length !== 1) {
          throw createCliError(
            'COMPONENT_SELECTION_REQUIRED',
            'Select exactly one project component.'
          );
        }
        const target = path.join(
          roots[0],
          '.github',
          'workflows',
          'lee-spec-kit-knowledge.yml'
        );
        const content = buildKnowledgeWorkflow(
          config.workflow?.baseBranch || 'main',
          config.lang,
          program.version() || '0.0.0',
          { autoMerge: options.autoMerge === true }
        );
        await fs.ensureDir(path.dirname(target));
        let workflowUpdated = false;
        if (await fs.pathExists(target)) {
          const existing = await fs.readFile(target, 'utf8');
          if (existing !== content) {
            const recognizedLegacyWorkflow =
              existing.startsWith('# Generated by lee-spec-kit.') &&
              existing.includes('lee-spec-kit knowledge update --ci') &&
              existing.includes('Avoid repeating a failed scheduled revision');
            if (!recognizedLegacyWorkflow) {
              throw createCliError(
                'OPENWIKI_CI_EXISTS',
                'An existing workflow differs and is not a recognized generated legacy workflow; update it manually instead of overwriting customizations.'
              );
            }
            await fs.writeFile(target, content);
            workflowUpdated = true;
          }
        } else {
          await fs.writeFile(target, content, { flag: 'wx' });
        }
        const instructions = path.join(roots[0], 'openwiki', 'INSTRUCTIONS.md');
        let instructionsCreated = false;
        if (!(await fs.pathExists(instructions))) {
          await fs.ensureDir(path.dirname(instructions));
          await fs.copyFile(
            path.join(getResourcesDir(), 'openwiki', 'INSTRUCTIONS.md'),
            instructions,
            fs.constants.COPYFILE_EXCL
          );
          instructionsCreated = true;
        }
        const ignore = path.join(roots[0], '.openwikiignore');
        const ignoreUpdated = await ensureKnowledgeSourceIgnore(ignore);
        return {
          status: 'ok',
          reasonCode: 'OPENWIKI_CI_READY',
          path: target,
          workflowUpdated,
          instructions,
          instructionsCreated,
          ignore,
          ignoreUpdated,
          executionOwner: 'openwiki',
        };
      });
    });

  knowledge
    .command('migrate')
    .description('Dry-run legacy Curated Documentation Impact grandfathering')
    .option(
      '--apply',
      'Mark only approved, terminal, committed legacy Features as grandfathered'
    )
    .option('--json', 'Output JSON')
    .action(async (options: KnowledgeOptions) => {
      await handleKnowledgeAction(options, async () =>
        migrateLegacyDocumentationImpact(process.cwd(), options.apply === true)
      );
    });
}

async function ensureKnowledgeSourceIgnore(
  ignorePath: string
): Promise<boolean> {
  const existing = (await fs.pathExists(ignorePath))
    ? await fs.readFile(ignorePath, 'utf8')
    : '';
  const start = existing.indexOf(KNOWLEDGE_IGNORE_BEGIN);
  const end = existing.indexOf(KNOWLEDGE_IGNORE_END);
  if ((start === -1) !== (end === -1) || (start !== -1 && end < start)) {
    throw createCliError(
      'OPENWIKI_IGNORE_BLOCK_INVALID',
      'The lee-spec-kit Knowledge source-ignore block is incomplete.'
    );
  }
  const updated =
    start === -1
      ? `${existing.trimEnd()}${existing.trimEnd() ? '\n\n' : ''}${KNOWLEDGE_IGNORE_BLOCK}\n`
      : existing.slice(0, start) +
        KNOWLEDGE_IGNORE_BLOCK +
        existing.slice(end + KNOWLEDGE_IGNORE_END.length);
  if (updated === existing) return false;
  await fs.writeFile(ignorePath, updated);
  return true;
}

async function migrateLegacyDocumentationImpact(
  cwd: string,
  apply: boolean
): Promise<unknown> {
  const config = await getConfig(cwd);
  if (!config) {
    throw createCliError(
      'CONFIG_NOT_FOUND',
      'Config file not found. Run `init` first.'
    );
  }
  const selection = await resolveFeatureSelection(cwd);
  const assess = async () => {
    const changedPaths: string[] = [];
    const results: Array<{
      featureRef: string;
      component: string;
      status: 'current' | 'grandfathered' | 'eligible' | 'manual_review';
      schemaStatus: string;
      reason: string;
      planPath: string;
    }> = [];
    for (const feature of selection.features) {
      const specPath = path.join(feature.path, 'spec.md');
      const planPath = path.join(feature.path, 'plan.md');
      const tasksPath = path.join(feature.path, 'tasks.md');
      const [spec, plan, tasks] = await Promise.all([
        fs
          .pathExists(specPath)
          .then((exists) => (exists ? fs.readFile(specPath, 'utf-8') : '')),
        fs
          .pathExists(planPath)
          .then((exists) => (exists ? fs.readFile(planPath, 'utf-8') : '')),
        fs
          .pathExists(tasksPath)
          .then((exists) => (exists ? fs.readFile(tasksPath, 'utf-8') : '')),
      ]);
      const impact = parseCuratedDocumentationImpact(plan);
      const base = {
        featureRef: feature.folderName,
        component: feature.type,
        planPath,
        schemaStatus: impact.schemaStatus,
      };
      if (impact.schemaStatus === 'current-v2' && impact.valid) {
        results.push({
          ...base,
          status: 'current',
          reason: 'Curated Documentation Impact is already valid.',
        });
        continue;
      }
      if (impact.grandfathered) {
        const terminal = isTerminalFeatureForCuratedImpact({
          spec,
          plan,
          tasks,
        });
        const currentFingerprint = await computeFeatureDocumentationFingerprint(
          feature.path
        );
        const gitState = inspectCommittedFeatureDocs(
          feature.git.docsGitCwd,
          feature.path
        );
        const validGrandfather =
          terminal.terminal &&
          gitState === 'committed' &&
          impact.grandfatheredFingerprint === currentFingerprint;
        results.push({
          ...base,
          status: validGrandfather ? 'grandfathered' : 'manual_review',
          reason: validGrandfather
            ? 'The provenance-bound legacy policy marker is valid.'
            : `The grandfather marker is stale or the Feature is no longer terminal (gitState=${gitState}; ${terminal.reasons.join(', ') || 'feature documentation fingerprint changed'}).`,
        });
        continue;
      }
      if (impact.schemaStatus === 'partial') {
        results.push({
          ...base,
          status: 'manual_review',
          reason: `An incomplete assessment must not be grandfathered: ${impact.errors.join(' ')}`,
        });
        continue;
      }
      const terminal = isTerminalFeatureForCuratedImpact({
        spec,
        plan,
        tasks,
      });
      const gitState = inspectCommittedFeatureDocs(
        feature.git.docsGitCwd,
        feature.path
      );
      if (!terminal.terminal || gitState !== 'committed') {
        results.push({
          ...base,
          status: 'manual_review',
          reason: `Only approved, terminal, fully committed legacy Features are eligible (gitState=${gitState}; ${terminal.reasons.join(', ') || 'terminal document state confirmed'}).`,
        });
        continue;
      }
      if (apply) {
        const fingerprint = await computeFeatureDocumentationFingerprint(
          feature.path
        );
        const next = `${removeCuratedImpactGrandfatherMarkers(plan)}\n\n${buildCuratedImpactGrandfatherMarker(fingerprint)}\n`;
        const temporary = `${planPath}.${process.pid}.${randomUUID()}.tmp`;
        try {
          await fs.writeFile(temporary, next, {
            encoding: 'utf-8',
            flag: 'wx',
          });
          await fs.rename(temporary, planPath);
          changedPaths.push(planPath);
        } finally {
          await fs.remove(temporary).catch(() => undefined);
        }
      }
      results.push({
        ...base,
        schemaStatus: apply ? 'grandfathered' : impact.schemaStatus,
        status: apply ? 'grandfathered' : 'eligible',
        reason: apply
          ? 'Recorded a policy-cutover marker without inferring NONE decisions.'
          : 'Eligible for explicit --apply; dry-run made no changes.',
      });
    }
    return {
      status: 'ok',
      reasonCode: apply
        ? 'OPENWIKI_MIGRATION_APPLIED'
        : 'OPENWIKI_MIGRATION_DRY_RUN',
      dryRun: !apply,
      changed: changedPaths,
      features: results,
    };
  };
  return apply
    ? withFileLock(getDocsLockPath(config.docsDir), assess, {
        owner: 'openwiki:migrate',
      })
    : assess();
}

function inspectCommittedFeatureDocs(
  docsGitCwd: string,
  featurePath: string
): 'committed' | 'dirty' | 'unavailable' {
  try {
    const root = String(
      execFileSync('git', ['rev-parse', '--show-toplevel'], {
        cwd: docsGitCwd,
        encoding: 'utf-8',
        stdio: ['ignore', 'pipe', 'pipe'],
      })
    ).trim();
    const relative = path.relative(root, featurePath).replace(/\\/gu, '/');
    const tracked = String(
      execFileSync('git', ['ls-files', '--', relative], {
        cwd: root,
        encoding: 'utf-8',
        stdio: ['ignore', 'pipe', 'pipe'],
      })
    ).trim();
    const dirty = String(
      execFileSync(
        'git',
        ['status', '--porcelain=v1', '--untracked-files=all', '--', relative],
        {
          cwd: root,
          encoding: 'utf-8',
          stdio: ['ignore', 'pipe', 'pipe'],
        }
      )
    ).trim();
    return tracked && !dirty ? 'committed' : 'dirty';
  } catch {
    return 'unavailable';
  }
}

async function handleKnowledgeAction(
  options: KnowledgeOptions,
  action: () => Promise<unknown>
): Promise<void> {
  try {
    const payload = await action();
    if (options.json) {
      console.log(JSON.stringify(payload, null, 2));
      return;
    }
    const value = payload as { status?: string; reasonCode?: string };
    console.log(
      `${value.status || 'ok'}: ${value.reasonCode || 'OPENWIKI_OK'}`
    );
  } catch (error) {
    const cliError = toCliError(error);
    if (options.json) {
      console.log(
        JSON.stringify(
          {
            status: 'error',
            reasonCode: cliError.code,
            error: cliError.message,
            ...(cliError.details ? { details: cliError.details } : {}),
          },
          null,
          2
        )
      );
      process.exitCode = 1;
      return;
    }
    process.stderr.write(`[${cliError.code}] ${cliError.message}\n`);
    process.exitCode = 1;
  }
}
