/** GitHub.com artifact publication. No PR credentials or repository pushes. */
export function buildKnowledgeWorkflow(
  baseBranch: string,
  lang: string,
  version: string
): string {
  if (
    !/^[a-zA-Z0-9._/-]+$/u.test(baseBranch) ||
    !['ko', 'en'].includes(lang) ||
    !/^\d+\.\d+\.\d+(?:-[a-zA-Z0-9.-]+)?$/u.test(version)
  ) {
    throw new Error(
      'Unsupported workflow branch, language, or toolkit version.'
    );
  }
  return `# Generated by lee-spec-kit. Configure OPENAI_API_KEY in repository secrets.
# See https://github.com/actions/upload-artifact for hidden-file handling.
name: OpenWiki after integration
on:
  push:
    branches: [${JSON.stringify(baseBranch)}]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: openwiki-integration
  cancel-in-progress: true
jobs:
  knowledge:
    if: github.ref == 'refs/heads/${baseBranch}'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install generation tools
        run: npm install --global lee-spec-kit@${version} openwiki@0.5.0
      - name: Generate and validate integrated Knowledge
        id: knowledge
        env:
          OPENWIKI_PROVIDER: openai
          OPENAI_API_KEY: \${{ secrets.OPENAI_API_KEY }}
        run: |
          lee-spec-kit knowledge publish --ci --base-branch '${baseBranch}' --lang ${lang} --json > "$RUNNER_TEMP/knowledge-result.json"
          node --input-type=module -e 'import fs from "node:fs"; const result = JSON.parse(fs.readFileSync(process.env.RUNNER_TEMP + "/knowledge-result.json", "utf8")); if (result.status === "disabled") process.exit(0); if (result.status !== "ok" || !result.artifactPath) process.exit(1); fs.appendFileSync(process.env.GITHUB_OUTPUT, "artifact=" + result.artifactPath + "\\n");'
      - uses: actions/upload-artifact@v4
        if: steps.knowledge.outputs.artifact != ''
        with:
          name: openwiki-\${{ github.sha }}-\${{ github.run_attempt }}
          path: \${{ steps.knowledge.outputs.artifact }}
          include-hidden-files: true
          if-no-files-found: error
`;
}
