import { OPENWIKI_VERIFIED_VERSION } from './openwiki-knowledge.js';

/** GitHub.com scheduled publication into one reusable Knowledge-only PR. */
export function buildKnowledgeWorkflow(
  baseBranch: string,
  lang: string,
  version: string
): string {
  if (
    !/^[a-zA-Z0-9._/-]+$/u.test(baseBranch) ||
    !['ko', 'en'].includes(lang) ||
    !/^\d+\.\d+\.\d+(?:-[a-zA-Z0-9.-]+)?$/u.test(version)
  ) {
    throw new Error(
      'Unsupported workflow branch, language, or toolkit version.'
    );
  }
  return `# Generated by lee-spec-kit. Configure OPENAI_API_KEY in repository secrets.
name: Scheduled OpenWiki Knowledge
on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:
permissions:
  actions: read
  contents: write
  pull-requests: write
concurrency:
  group: openwiki-knowledge-${baseBranch}
  cancel-in-progress: false
jobs:
  knowledge:
    runs-on: ubuntu-latest
    env:
      KNOWLEDGE_BRANCH: lee-spec-kit/knowledge-${baseBranch.replaceAll('/', '-')}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${baseBranch}'
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install generation tools
        run: npm install --global lee-spec-kit@${version} openwiki@${OPENWIKI_VERIFIED_VERSION}
      - name: Record source revision
        id: source
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - name: Reuse the open Knowledge pull request when it already covers this revision
        id: reuse
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          if git ls-remote --exit-code --heads origin "refs/heads/$KNOWLEDGE_BRANCH" >/dev/null 2>&1; then
            base="$(git rev-parse HEAD)"
            git fetch origin "refs/heads/$KNOWLEDGE_BRANCH:refs/remotes/origin/$KNOWLEDGE_BRANCH"
            echo 'baseline=true' >> "$GITHUB_OUTPUT"
            git switch --detach "refs/remotes/origin/$KNOWLEDGE_BRANCH"
            lee-spec-kit knowledge status --ci --base-branch '${baseBranch}' --lang ${lang} --json > "$RUNNER_TEMP/knowledge-existing.json"
            covered="$(BASE_REVISION="$base" node --input-type=module -e 'import fs from "node:fs"; const result = JSON.parse(fs.readFileSync(process.env.RUNNER_TEMP + "/knowledge-existing.json", "utf8")); process.stdout.write(String(result.knowledge?.status === "current" && result.knowledge?.publishedRevision === process.env.BASE_REVISION));')"
            if [ "$covered" = 'true' ]; then
              existing="$(gh pr list --head "$KNOWLEDGE_BRANCH" --base '${baseBranch}' --state open --json url --jq '.[0].url // empty')"
              if [ -z "$existing" ]; then
                gh pr create --head "$KNOWLEDGE_BRANCH" --base '${baseBranch}' --title 'docs: refresh OpenWiki Knowledge' --body 'Scheduled lee-spec-kit update derived from the current project code revision.'
              fi
              echo 'current=true' >> "$GITHUB_OUTPUT"
            fi
            git switch -C '${baseBranch}' "$base"
          fi
      - name: Avoid repeating a failed scheduled revision
        id: prior_failure
        if: github.event_name == 'schedule' && steps.reuse.outputs.current != 'true'
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          name="lee-spec-kit-knowledge-failure-\${{ steps.source.outputs.sha }}"
          count="$(gh api "repos/\${{ github.repository }}/actions/artifacts?name=$name" --jq '.artifacts | map(select(.expired == false)) | length')"
          failed_runs="$(gh api "repos/\${{ github.repository }}/actions/workflows/lee-spec-kit-knowledge.yml/runs?event=schedule&per_page=100" --jq '[.workflow_runs[] | select(.id != \${{ github.run_id }} and .head_sha == "\${{ steps.source.outputs.sha }}" and (.conclusion == "failure" or .conclusion == "cancelled" or .conclusion == "timed_out"))] | length')"
          if [ "$count" -gt 0 ] || [ "$failed_runs" -gt 0 ]; then
            echo 'blocked=true' >> "$GITHUB_OUTPUT"
            echo 'A prior scheduled attempt for this exact revision failed or was externally terminated. Inspect its workflow result and any sanitized diagnostic artifact, then use workflow_dispatch to retry.' >&2
            exit 1
          fi
      - name: Generate and validate integrated Knowledge
        id: knowledge
        if: steps.reuse.outputs.current != 'true' && steps.prior_failure.outputs.blocked != 'true'
        env:
          OPENWIKI_PROVIDER: openai
          OPENAI_API_KEY: \${{ secrets.OPENAI_API_KEY }}
        run: |
          set +e
          baseline_args=()
          if [ "\${{ steps.reuse.outputs.baseline }}" = 'true' ]; then
            baseline_args=(--baseline-ref "refs/remotes/origin/$KNOWLEDGE_BRANCH")
          fi
          lee-spec-kit knowledge update --ci --base-branch '${baseBranch}' --lang ${lang} "\${baseline_args[@]}" --json > "$RUNNER_TEMP/knowledge-result.json"
          code=$?
          set -e
          cat "$RUNNER_TEMP/knowledge-result.json"
          common="$(git rev-parse --git-common-dir)"
          cp "$common/lee-spec-kit.runtime/knowledge/status.json" "$RUNNER_TEMP/knowledge-status.json" 2>/dev/null || true
          if [ "$code" -ne 0 ]; then exit "$code"; fi
          node --input-type=module -e 'import fs from "node:fs"; const result = JSON.parse(fs.readFileSync(process.env.RUNNER_TEMP + "/knowledge-result.json", "utf8")); if (result.status === "disabled" || result.unchanged === true) process.exit(0); if (result.status !== "ok" || !result.artifactPath) process.exit(1); fs.appendFileSync(process.env.GITHUB_OUTPUT, "artifact=" + result.artifactPath + "\\n");'
      - name: Install project dependencies for repository commit hooks
        if: steps.knowledge.outputs.artifact != ''
        run: |
          if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile
          elif [ -f yarn.lock ]; then corepack enable && yarn install --immutable
          elif [ -f package-lock.json ]; then npm ci
          elif [ -f package.json ]; then npm install
          fi
      - name: Apply verified Knowledge only
        id: apply
        if: steps.knowledge.outputs.artifact != ''
        run: |
          git config user.name 'lee-spec-kit Knowledge'
          git config user.email 'knowledge@lee-spec-kit.invalid'
          before="$(git rev-parse HEAD)"
          set +e
          lee-spec-kit knowledge apply --ci --base-branch '${baseBranch}' --lang ${lang} --json > "$RUNNER_TEMP/knowledge-apply.json"
          code=$?
          set -e
          cat "$RUNNER_TEMP/knowledge-apply.json"
          if [ "$code" -ne 0 ]; then exit "$code"; fi
          after="$(git rev-parse HEAD)"
          if [ "$before" != "$after" ]; then echo 'changed=true' >> "$GITHUB_OUTPUT"; fi
      - name: Update Knowledge pull request
        if: steps.apply.outputs.changed == 'true'
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          git push --force-with-lease origin "HEAD:refs/heads/$KNOWLEDGE_BRANCH"
          existing="$(gh pr list --head "$KNOWLEDGE_BRANCH" --base '${baseBranch}' --state open --json url --jq '.[0].url // empty')"
          if [ -z "$existing" ]; then
            gh pr create --head "$KNOWLEDGE_BRANCH" --base '${baseBranch}' --title 'docs: refresh OpenWiki Knowledge' --body 'Scheduled lee-spec-kit update derived from the current project code revision.'
          fi
      - name: Collect sanitized diagnostics and partial-output inventory
        if: failure()
        run: |
          diagnostic="$RUNNER_TEMP/knowledge-diagnostics"
          mkdir -p "$diagnostic"
          run="$(node --input-type=module -e 'import fs from "node:fs"; try { const value = JSON.parse(fs.readFileSync(process.env.RUNNER_TEMP + "/knowledge-status.json", "utf8")); const candidate = value?.details?.worktree || value?.worktree || ""; if (typeof candidate === "string") process.stdout.write(candidate); } catch {}')"
          RUN_PATH="$run" node --input-type=module <<'NODE'
          import fs from 'node:fs';
          import path from 'node:path';
          const temp = process.env.RUNNER_TEMP;
          const target = path.join(temp, 'knowledge-diagnostics');
          const blocked = /outputtail|stdout|stderr|prompt|token|authorization|api.?key|access.?key|secret|credential/i;
          const clean = (value) => Array.isArray(value)
            ? value.map(clean)
            : value && typeof value === 'object'
              ? Object.fromEntries(Object.entries(value).filter(([key]) => !blocked.test(key)).map(([key, item]) => [key, clean(item)]))
              : value;
          const copyJson = (source, name) => {
            try { fs.writeFileSync(path.join(target, name), JSON.stringify(clean(JSON.parse(fs.readFileSync(source, 'utf8'))), null, 2) + '\\n'); } catch {}
          };
          for (const name of ['knowledge-result.json', 'knowledge-status.json', 'knowledge-apply.json', 'knowledge-existing.json']) copyJson(path.join(temp, name), name);
          const run = process.env.RUN_PATH;
          if (run) {
            copyJson(path.join(run, '.lee-spec-kit', 'openwiki-run.json'), 'openwiki-run.json');
            copyJson(path.join(run, '.lee-spec-kit', 'openwiki-sync.json'), 'openwiki-sync.json');
            const root = path.join(run, 'openwiki');
            const files = [];
            const visit = (directory) => {
              for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
                const absolute = path.join(directory, entry.name);
                if (entry.isDirectory()) visit(absolute);
                else if (entry.isFile() && entry.name !== '.run.json') files.push({ path: path.relative(root, absolute).replaceAll(path.sep, '/'), bytes: fs.statSync(absolute).size });
              }
            };
            try { visit(root); } catch {}
            fs.writeFileSync(path.join(target, 'partial-output-inventory.json'), JSON.stringify({ files }, null, 2) + '\\n');
          }
          NODE
      - name: Preserve sanitized Knowledge diagnostics
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lee-spec-kit-knowledge-failure-\${{ steps.source.outputs.sha }}
          if-no-files-found: ignore
          retention-days: 14
          path: \${{ runner.temp }}/knowledge-diagnostics/
`;
}
